### ISSUE TITLE
Vertaisarviointi 2.

### ISSUE THREAD

**Issue by JanneKarki** [Capslock01/project-manager#2]
21.6.22 Sovellusta testailtu välillä 21:20-22:20

Sovellus on hyvässä vaiheessa, jonka ulkoasu on viimeistelty ja hieno.  Sovellus vaatii aluksi hieman opettelua, mutta hetken käytön jälkeen kokonaisuus alkaa selkiytyä. Jokaisella syötteellä on selkeät infot ja navigointi sovelluksessa on helppoa. Kirjautumisen jälkeen olisin odottanut siirtymistä suoraan app sivulle. Kun ensimmäistä projektia luo, sovellus ilmoittaa, että täytyy luoda yritys ensin. Vaikka uuden yrityksen luonti löytyy yläpalkista, ilmoituksessa voisi olla myös sinne linkki, jolloin ensikokemus olisi sujuvampi. Uutta worktypeä luodessa sovellus kaatui syötteillä Consult, 60, 60, 150. Myöhemmin testatessa samat syötteet, eivät kuitenkaan aiheuttaneet sovelluksen kaatumista. €-laskelma tehdyistä töistä olisi kiva lisä. Oikein mukavakäyttöinen sovellus.

Koodin muuttujat ja funktiot on kuvaavasti nimetty. Koodin moduulijako on hieman erillainen, kuin miten itse rakensin kurssin esimerkkejä seuraillen, joten koodin seurailu vaatii hieman erillaista hahmotusta, mutta syy voi olla nyt arvioijassa. Jotkin funktioista on pitkiä, joten niiden pilkkominen osiin, niin että suorittavat vain yhtä toimintoa kerrallaan, saattaisivat allekirjoitaneen mielestä olla paikallaan. #-kommentit ovat kyllä kuvaavia, mikä kyllä ajaa melkein saman asian.  Tietokantaoperaatiot voisivat esimerkiksi olla omia funktioitaan. Voi myös olla, että on kysessä erillainen ohjelmointityyli. Ei riitä arvioijan kokemus sanomaan. 😊 Pitkiä ja monitoimintaisia funktioita olivat: new_company.py: add_company(),  newproject.py: create_worktype(), newworktype.py:create_worktype(), stop.py add_rounding_entry().

**Comment by Capscience** [comment]
Kiitos arvioinnista. Toiminnallisuuteen liittyvät asiat ovat onneksi melko pieniä, mutta erittäin hyviä huomioita. Worktypen luontiin liittyvä crash johtui siitä, että pushasin juurikin 21:58 uuden version sovelluksesta herokuun. Hintalaskelmat ovatkin suunnitelluissa ominaisuuksissa.

Sovelluksen rakenteen osalta pyrin mahdollisimman selkeään kokonaisuuteen, eli jokainen toiminnallisuus/path on omassa tiedostossaan. Src-hakemistossa on sitten kaikki tiedostot yhdellä kertaa nähtävissä. Sovellus on suunniteltu lähes kokonaan käyttämättä OOP-tyyliä, sillä se tuntui tähän tapaukseen selkeämmältä.

Aivan kaikista mainitsemistasi funktioista en ole samaa mieltä, että olisi liian pitkiä, mutta osassa on vielä selkeästi siistimistä. Käyn kaikki läpi huolella, kun teen tässä vielä erikseen koodin siistintää. Kiitos hyvistä nostoista!
